# Generated by Django 5.2.5 on 2025-10-15 13:12

from typing import TYPE_CHECKING

from django.db import migrations

if TYPE_CHECKING:
    from api.models import Category


def create_default_categories(apps, schema_editor):
    category: Category = apps.get_model('api', 'Category')
    category.objects.get_or_create(name='Income', parent=True)
    category.objects.get_or_create(name='Expense', parent=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
