# Generated by Django 5.2.5 on 2025-10-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
